services:

  # --- BANCO DE DADOS ---
  db:
    image: postgres:15-alpine
    container_name: onesid-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onesid_db
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    networks:
      - onesid-net

  # --- LOKI (Coletor de Logs) ---
  loki:
    image: grafana/loki:2.9.2
    container_name: onesid-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - onesid-net

networks:
  onesid-net:
    driver: bridge