services:

  # --- BANCO DE DADOS ---
  # Apenas o Postgres vai rodar no Docker
  db:
    image: postgres:15-alpine
    container_name: onesid-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onesid_db
    ports:
      # Exp√µe a porta 5432 do container para a 5432 do seu PC
      - "5432:5432" 
    volumes:
      # Salva os dados na pasta 'postgres_data' do seu projeto
      - ./postgres_data:/var/lib/postgresql/data 
    networks:
      - onesid-net

networks:
  onesid-net:
    driver: bridge